theme: jekyll-theme-slate
title: Frontend Mentor projects - Jordan Falaise
description: This web page's main purpose is to host my Frontend Mentor projects while working on my own on a proper blog/website.
